### ISSUE TITLE
Docs for distros of ZeTriUm

### ISSUE THREAD

**Issue by thoughtfulonion** [aguslr/multibootusb#230]
I want to document all the distros added by @ZeTriUm. But since they are quit a few it still in progress:

- [x] #187  GeckoLinux
- [x] #186 ArchLabs 
- [x] #185  Maui Linux
- [x] #184 ArchStrike
- [x] #183 Runtu 
- [x] #182 Chakra GNU/Linux 
- [x] #181 RoboLinux
- [ ] #180 Scientific Linux
- [ ] #179 Calculate Linux
- [ ] #178 SolydXK
- [ ] #177 OSGeo-Live
- [ ] #176 Siduction
- [ ] #175 JanusLinux
- [ ] #174  Musix GNU+Linux
- [ ] #173 Liquid Lemur Linux
- [ ] #172 OPNsense
- [ ] #171 Exton Linux Live
- [ ] #170 Voyager
- [ ] #169 Revenge OS
- [ ] #168 Red Flag Linux
- [ ] #167 Qomo Linux
- [ ] #166 Phoenix OS
- [ ] #164 LinHES
- [ ] #163 ClearOS
- [ ] #162 Bluestar Linux
- [ ] #161 Bliss OS
- [ ] #160 Plop Linux
- [ ] #159 Pop!_OS
- [ ] #158 Ubuntu Kylin
- [ ] #157 Emmabuntüs
- [ ] #156 CyanogenMod

If you want to help:

The documentation files are written in Markdown and generated by [Jekyll](https://jekyllrb.com/).
They can be tested by installing [Ruby](https://www.ruby-lang.org) and running:

```
gem install jekyll bundler github-pages
cd multibootusb/docs
bundle exec jekyll serve
```
